version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Add environment variables here, for example:
      NODE_ENV: production
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start
